//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialMarketPredictor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialMarketPredictor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad parameters.
        /// </summary>
        internal static string BadParameters {
            get {
                return ResourceManager.GetString("BadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to change the network. Previous predictor will be lost!.
        /// </summary>
        internal static string ChangedNetwork {
            get {
                return ResourceManager.GetString("ChangedNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.csv)|*.csv.
        /// </summary>
        internal static string CsvFilter {
            get {
                return ResourceManager.GetString("CsvFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured while loading the network!.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File missing.
        /// </summary>
        internal static string FileMissing {
            get {
                return ResourceManager.GetString("FileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the input files is missing, please recheck files with indexes.
        /// </summary>
        internal static string InputMissing {
            get {
                return ResourceManager.GetString("InputMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network.
        /// </summary>
        internal static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.ntwrk)|*.ntwrk.
        /// </summary>
        internal static string NtwrkFilter {
            get {
                return ResourceManager.GetString("NtwrkFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Predict From&quot; should be bigger than &quot;Predict To&quot; parameter.
        /// </summary>
        internal static string PredictFromToWarning {
            get {
                return ResourceManager.GetString("PredictFromToWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security exception.
        /// </summary>
        internal static string SecurityException {
            get {
                return ResourceManager.GetString("SecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have required permissions to read from this folder.
        /// </summary>
        internal static string SecurityExceptionFolderLevel {
            get {
                return ResourceManager.GetString("SecurityExceptionFolderLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough permissions to save the network in the specified path.
        /// </summary>
        internal static string SecurityExceptionMessage {
            get {
                return ResourceManager.GetString("SecurityExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Train From&quot; should be bigger than &quot;Train To&quot; parameter.
        /// </summary>
        internal static string TrainFromTrainTo {
            get {
                return ResourceManager.GetString("TrainFromTrainTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The predictor, is not trained. Whould you like to continue with untrained network? Press
        ///[Yes] to continue
        ///[No] to load a saved network
        ///[Cancel] to return.
        /// </summary>
        internal static string UntrainedPredictorWarning {
            get {
                return ResourceManager.GetString("UntrainedPredictorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
